"use client";
import { useState } from "react";

export type Opponent={id:number;team:string;season_pa:number;season_so:number;vs_l_pa:number;vs_l_so:number;vs_r_pa:number;vs_r_so:number;last_30_pa:number;last_30_so:number};
export type Pitcher={id:number;name:string;hand:"L"|"R";team:string;tbf:number;strikeouts:number;bf_per_ip:number;projected_ip:number;context:number};
export type Game={id:number;game_date:string;away_team:string;home_team:string;away_pitcher:string;home_pitcher:string;k_line:number;over_odds:number;under_odds:number};

export function DataManager({opponents,pitchers,games,onRefresh}:{opponents:Opponent[];pitchers:Pitcher[];games:Game[];onRefresh:()=>void}){
 const [tab,setTab]=useState<"games"|"opponents"|"pitchers">("games"),[editing,setEditing]=useState<Record<string,unknown>|null>(null),[notice,setNotice]=useState("");
 const records=tab==="games"?games:tab==="opponents"?opponents:pitchers;
 const startNew=()=>setEditing(tab==="games"?{game_date:new Date().toISOString().slice(0,10),away_team:"",home_team:"",away_pitcher:"",home_pitcher:"",k_line:4.5,over_odds:1.9,under_odds:1.9}:tab==="pitchers"?{name:"",hand:"R",team:"",tbf:0,strikeouts:0,bf_per_ip:4.2,projected_ip:5.5,context:1}:{team:"",season_pa:0,season_so:0,vs_l_pa:0,vs_l_so:0,vs_r_pa:0,vs_r_so:0,last_30_pa:0,last_30_so:0});
 const save=async()=>{if(!editing)return;setNotice("Saving…");const res=await fetch("/api/data",{method:editing.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entity:tab,...editing})});const body=await res.json() as {error?:string};if(!res.ok){setNotice(body.error??"Could not save");return;}setNotice("Saved");setEditing(null);onRefresh();};
 const remove=async(id:number)=>{await fetch("/api/data",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({entity:tab,id})});onRefresh();};
 const fields=tab==="games"?["game_date","away_team","home_team","away_pitcher","home_pitcher","k_line","over_odds","under_odds"]:tab==="pitchers"?["name","hand","team","tbf","strikeouts","bf_per_ip","projected_ip","context"]:["team","season_pa","season_so","vs_l_pa","vs_l_so","vs_r_pa","vs_r_so","last_30_pa","last_30_so"];
 return <section className="data-admin" id="data"><div className="section-title"><div><span className="eyebrow">DATA CENTER</span><h2>Keep the model current.</h2></div><button onClick={startNew}>+ ADD RECORD</button></div>
  <div className="data-tabs"><button className={tab==="games"?"selected":""} onClick={()=>{setTab("games");setEditing(null)}}>DAILY SCHEDULE <b>{games.length}</b></button><button className={tab==="opponents"?"selected":""} onClick={()=>{setTab("opponents");setEditing(null)}}>OPPONENT DATA <b>{opponents.length}</b></button><button className={tab==="pitchers"?"selected":""} onClick={()=>{setTab("pitchers");setEditing(null)}}>PITCHER DATA <b>{pitchers.length}</b></button></div>
  {editing&&<div className="editor"><div className="editor-grid">{fields.map(field=><label key={field}><span>{field.replaceAll("_"," ")}</span>{field==="hand"?<select value={String(editing[field]??"")} onChange={e=>setEditing({...editing,[field]:e.target.value})}><option>R</option><option>L</option></select>:<input type={field.includes("date")?"date":["team","name","away_team","home_team","away_pitcher","home_pitcher"].includes(field)?"text":"number"} step="any" value={String(editing[field]??"")} onChange={e=>setEditing({...editing,[field]:e.target.type==="number"?Number(e.target.value):e.target.value})}/>}</label>)}</div><div className="editor-actions"><button onClick={save}>SAVE RECORD</button><button onClick={()=>setEditing(null)}>CANCEL</button><span>{notice}</span></div></div>}
  <div className="records">{records.length===0?<p className="empty">No records yet. Add the first one to begin.</p>:records.map((r:any)=><div className="record" key={r.id}><div><b>{tab==="games"?`${r.away_team} @ ${r.home_team}`:tab==="pitchers"?r.name:r.team}</b><small>{tab==="games"?`${r.game_date} · ${r.away_pitcher} / ${r.home_pitcher}`:tab==="pitchers"?`${r.hand}HP · ${r.team} · ${r.strikeouts} K / ${r.tbf} TBF`:`Season ${(r.season_so/r.season_pa*100).toFixed(1)}% · LHP ${(r.vs_l_so/r.vs_l_pa*100).toFixed(1)}% · RHP ${(r.vs_r_so/r.vs_r_pa*100).toFixed(1)}%`}</small></div><div><button onClick={()=>setEditing({...r})}>EDIT</button><button className="delete" onClick={()=>remove(r.id)}>DELETE</button></div></div>)}</div>
 </section>;
}
